### ISSUE TITLE
[Project_FIFA_MoneyBall] Susumu Sakamoto

### ISSUE THREAD

**Issue by susumusakamoto** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#10]
https://github.com/susumusakamoto/Project_FIFA_MoneyBall.git

**Comment by AnaAGG** [comment]
# ⚽️ Money Ball FIFA project ⚽️

Hi Susumu, here I am with the first project review. 

## Readme

- Suuper that you start your readme with the objective of your project Susumu! This is a good practice 

- Good job with the markdown formats Susumu, to be picky when we are working with markdown we can also create links to other pages. For example, in your readme you include two links from different websites, to make your readme cleaner:

  To get information which clubs belongs to which leagues https://www.ea.com/games/fifa/fifa-21/news/fifa-21-all-leagues-clubs-teams

  How can we include link in markdown?

        [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)

        If you use this structure you create a link like the ones we create for you when we send you documentation. 

        Example 👇🏽👇🏽

    [Here](https://www.markdownguide.org/cheat-sheet/) a markdown cheat-sheet in case it help you in the future

- Regarding the used tools, perfect that you include it in the readme 🤩. It will be perfect if you also include the link to the official documentation website. 

- What happened with the `6. Analysing Linear Regression Models` section? You have the header but no information there 🤔. I encourage you to include all the missing info therem to have a perfect readme Susumuuu

- Suuper that you include a "TODOs" section at the end of the readme to be aware of the limitation your work may have
## Repo structure

Nothing to tell you ons this part Susumu, you have a very well organised repo. You have created different folders where you keep the data and image, and the most important! No temporary files such as `vscode` or `DS_Store` have been left out of the gitignore. 

I would also like to congratulate you on the cleanliness of your jupyter. I really liked how in the model part you have been trying different methods and how you have been making a recap in each one of them to make it easy to follow 🔝🔝.


## Code syntax
- Just as detail, in the point 2.5 *Changing data type of 'value' and 'wage' from object to string*. In pandas, an `object` is a `string`, so it is the same and it would not be necessary to convert it. 

- In the same point (*Changing data type of 'value' and 'wage' from object to string*), you have repeated many times the same code to clean different columns (`value`, `wage` and `release_clause`). We should avoid repeated code in our works. What can we do? Write a function!!! In your case:
    ```python
    def clean_string(df, col):
        df[col] = df_original[col].str.strip('€')
        df[col] = (df[col].replace(r'[KMB]', '', regex=True).astype(float) *
            df[col].str.extract(r'[\d\.]+([KMB]+)', expand=False).fillna(1)
            .replace(['K','M','B'], [1, 10**3, 10**6]).astype(float))
        return df
    df = clean_string(df, "wage") # here it is important to pass the column name as string. 


    # Finally to avoid repeating the orevious line multiple times you can: 

    # create a list with the names of the columns that you are interested in
    lst_columns = ["wage", "value", "release_clause"]

    # and then iterate over the list and apply the function
    for i in lst_columns:
        df = clean_string(df, i)
    ```
  In the same way, you can create more function to clean ★ or create scales.  

- One thing that I recomended to you, specially with dataframes with a lot of columns, is firstly create a subset with the important columns. In this project, you have done a great job of researching the data, so you know what variables are important for your objective. 
Why is it a good practice? 
  - It will make your dataset smaller and easier to work with.
  - For example, when you create displots, you are creating a lot of plots that you don't really care about.
  
  Bassically avoid giving information that is not usefull and can be distracting. 

- Just a detail, in python there is a convention by which the imports go to the begining od the jupyter. 
  
- With the models, if you look at the models, you keep repeating the same code, but changing the data with which you fit the model. What can we do?? A Function!!!
    ```python
    def linear_regression(X, y):
        # this function receive two parameters, the x and y dataset 
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        model = LinearRegression()
        model.fit(X_train, y_train)

        predictions = model.predict(X_test)

        return r2_score(y_test, predictions), mean_absolute_error(y_test, predictions), mean_squared_error(y_test, predictions, squared=False)
    #So the only thing that you should do is define the different datasets and then "call" the function. 
    X = df_20f[['ova']]
    y = df_20f['value']

    linear_regression(X,y)

    # in order to avoid repeating the same code over and over again.
    ```

## TODOs

- Some visualization for example with the tables that you get with the most valued players. Your tables and results show clearly your hypothesis, but visualization could be more friendly for a person (or customer) who is not familiar with python. 
Remember, you have a lot of libraries in python that you could use with this objetive, my favorite... [plotly](https://plotly.com/python/plotly-express/)

- More function that will make your jupyter cleaner, and help us to simplyfy our code somewhat


All in all Susumu, you have done an amazing job on your first project. In this project you have reinforced the knowledge acquired so far in the bootcamp. You have explored the data, familiarised yourself with it, cleaned it and created a machine learning model with very good results, and you have added more data, amazing🚀🚀🔥🔥!!!!

![image](https://user-images.githubusercontent.com/75084991/126037144-0c45ead3-907c-47de-ae33-835c35bb5a1e.png)
