### ISSUE TITLE
[ignacio] Project_FIFA_MoneyBall

### ISSUE THREAD

**Issue by ignaciolorenzo** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#15]
https://github.com/ignaciolorenzo/ih-project1-moneyball

**Comment by fromeropablo** [comment]
# Moneyball Project

Hi Ignacio! Let's go with corrections of your first project as a Data Analyst! That's a big step after all the labs done and I do hope that you have enjoyed the process during the week to complete your project! 

Yu have done a good work here to be your first project, but you didn't propose any question further than your Machine Learning model and it was an important goal for the project aswell. 

## 1. ReadME and Miscellanous

Your ReadME works fine and gives a good shot of what have you done in your project. 

However, you can improve it to engage more people when they'll see your repository. And you will think, how?

- At first sight, the structure of your ReadME is really good but flatten. You can improve it a lot doing a few easy and quick things. The most important is to work properly in a *markdown* file. If you wanna improve your structure adding bigger titles and subtitles in bold or cursive, here you have a very useful link:

https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. I saw that you did it in your section #4 adding the link of the sources of your data, that's great!

- Finally, it seems that you have done successfully your .gitignore file hiding your csv file on it, great work!

## 2. What about your code?

Your jupyter notebook is clearly well organized and your explanations about every step that you do are good. Remember that about that last point, you can always create a *markdown* cell to give your explanations more clearly.

Great that you have imported all your libraries and your data at the beginning of your notebook! It's a very important step to do in the same way from now, forever. It helps other people who take a look to your code to check your libraries and its tools as well as your data. 

### 2.1 Exploratory analysis

Your work here is really great, congrats for it! It's cool that you have used a lot of concepts learned in class such as defining `functions`, `list comprehension`, `apply & lambdas`, **Pandas** methods...

Absolutely brilliant that you have created function almost for every step that you have done, congrats! That's the way to go!

Just a thing about visualization. I missed some plots in your project to check the features of your variables or answering possible questions. Remember that you can use libraries such as `matplotlib`, `seaborn` or `plotly`.

Nothing else to say here, your cleaning process here is quite accurate trying to clean as columns as possible. You did a really great job here that you have to be proud of. 

### 2.2 Processing analysis

Once you cleaned all your data and you understood the variables you have to work with, it's time to do the processing analysis, which is the main step of a Machine Learning model. 

First of all, when you do some changes in your number of variables, you have to know how many of them you have. If your model can explain better the behavior of our target variable, it will better doing it with less variables. 

In your second attempt with the linear regression, take in count that, although you have a better R-Square, you also have a lot of extra variables which add so much noise to your model. Remember what I told you above. 

### 2.3 Questions

Good work here, your questions are really good showing the possible relation between important variables. Be careful to show properly your plots in your Github repo. 

I missed some more work on them, not just create a plot and show the correlation between variables, which are good choices in your case. 

If you work a little bit more in your project you will get a very good one to improve your portfolio, keep going!
