### ISSUE TITLE
Project_FIFA_MoneyBall Blandine

### ISSUE THREAD

**Issue by diebland** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#16]
https://github.com/diebland/MyProject_FIFA_MoneyBall

**Comment by Unaiat** [comment]
Hi Blandine 🙋‍♂️ Here I send you some feedback of the first project. 

I will start with some recommendation and finish with an overall summary:

Your readme is very good, you explain what you are going to do clearly. This helps to understand the code much better. You can also add images and gifs if you like it, with the following code:

```python
<img width=1000 src="path where the image is stored in your computer">
```

Something that would improve your project is to add more visualizations related to the hypothesis. Your questions are interesting, and you answer them properly. In the future, maybe try to think about hypothesis that could be proved or refuted also using visualizations. Thisis a practice that will be very helpful for your career. 

Finally, please also import all the libraries at the beginning 😀. You basically made it, except the `from sklearn.preprocessing import StandardScaler` and `import math` (imported twice, once is enough) `from scipy.special import inv_boxcox`. Again, this is a convention and not a mistake. 

All in all, you did a very good project, explaining the decisions you took and the reasoning behind them. This is very important, not only for the people that might check the code, but also for you. If you come back to the notebook later on, you will waste no time trying to remember the steps you took. 

Please, let us know if you have any question. 

Keep up the good work!!! 🚀
