### ISSUE TITLE
FIFA Moneyball Project - Jack

### ISSUE THREAD

**Issue by jack93g** [Ironhack-Data-0621-Remote/Project_FIFA_MoneyBall#4]
https://github.com/jack93g/FIFA-Moneyball-Project

**Comment by fromeropablo** [comment]
# Moneyball Project

Hi Jack! Let's go with corrections of your first project as a Data Analyst! That's a big step after all the labs done and I do hope that you have enjoyed the process during the week to complete your project! 

Yu have done a really good work here and you should be very happy for that. Keep working and showing tones of effort in your work, congrats!

## 1. ReadME and Miscellanous

Your ReadME works fine and gives a good shot of what have you done in your project. 

However, you can improve it to engage more people when they'll see your repository. And you will think, how?

- At first sight, the structured is not the best. You can improve it a lot doing a few easy and quick things. The most important is to work properly in a *markdown* file. If you wanna improve your structure adding bigger titles and subtitles in bold or cursive, here you have a very useful link:

https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd

- It's important to create a good storytelling. Your projects won't be just your code, idea and data, but also the way that you present it to the world! For example, you can add some images as I'm gonna show you:
```markdown
![Zones of the court](./images/polygon_court.png)
```
The first part of the line, the one inside square brackets, represents the words that should appear in case that the image doesn't show properly. The second part is the image itself. To do in the same way you should create a folder in your repo (from Visual Studio) called `images` and save the images you wanna show there.  

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```
Similar to what I told you before, the first part is the title or what every user will see in your repo and the second part is the link to the documentation of that module. It will appear in Github in blue words as a hyperlink. I saw that you did it in your section #4 adding the link of the sources of your data, that's great!

- The **.gitignore** file that you created had the purpose to hide the csv file that you worked with. It's as easy as open Visual Studio or PyCharm and go to the .gitignore file and type there the name of the file that you want to hide in Github. If you have any doubt about it, don't hesitate to contact me. 

- Absolutely great that you have uploaded an image with the best XI that you found. In addition, you added a *Images* folder to store your pictures there, brilliant! As a tip, your ReadME could open with that picture. It will reinforce your storytelling! 

## 2. What about your code?

Your jupyter notebook is clearly well organized and your explanations about every step that you do are good. Remember that about that last point, you can always create a *markdown* cell to give your explanations more clearly.

Great that you have imported all your libraries and your data at the beginning of your notebook! It's a very important step to do in the same way from now, forever. It helps other people who take a look to your code to check your libraries and its tools as well as your data. 

### 2.1 Exploratory analysis

Your work here is really great, congrats for it! It's cool that you have used a lot of concepts learned in class such as `list comprehension`, `apply & lambdas`, `regex`, **Pandas** methods and functions.

Just some tips to improve: 

- When you use `str.replace` from Pandas for the *€* symbol, you can either create a function with the name os the as a parameter or create a list with the columns you want to replace the symbol and use a for loop to iterate by them. 
- To be honest, I don't get your function to clean player's contract date. You have created a variable called **x** where you substract its value by the same value and then sum 2021. That's not very useful to your code. Anyway, great work using the function and, afterwards, the `apply` method. 

### 2.2 Questions

Great election of questions to answer, congrats! They have a good level of complexity, could be useful for further approaches and they make sense for what it's happening in real life!

As I said, it's amazing that you have uploaded images with the best XI possible and also based on player potential, it's really cool to answer such an interesting question in a visual way. 

Great work using `seaborn` and `matplotlib` to plot your results and show in a prettier way.

### 2.3 Processing analysis

Once you cleaned all your data and you understood the variables you have to work with, it's time to do the processing analysis, which is the main step of a Machine Learning model. 

Perfect job here, mate, congrats, you solve this problem in such a brilliant way!! It's quite important to get a high R2 but as important as doing it with the less number of variables possible as you did!

Also, you have showed your results in a DataFrame to help readers understand them, that's a good point! 

I have nothing else to say in your project, just remember to import all your libraries and modules at the first cell of your jupyter notebook. Great work overall, it seems that you like football a lot and you enjoyed doing this project! Keep going in the same way!
